### PR TITLE
v0.4

### PR DESCRIPTION
**Pull request by jouni**
Work in progress. Opened a PR so that we can get a preview deployed in Netlify (see commit checks below, click `Show all checks` → `Details`)

~~Update: branch preview available here as well: https://v0-4--jelements.netlify.com~~

The main site deployment is actually from this branch now: https://jelements.netlify.com

### CODE REVIEW

**Comment by lkraav** [comment]
@jouni what's left to do here you think?

**Comment by jouni** [comment]
@lkraav thanks for asking. I have to admit, that I have 97 changes still pending locally 😅 

The biggest upcoming changes are to PortalMixin, StylableMixin, LightStyleElement (going to be a mixin as well) and AppLayout.

I’m also removing the `J` prefix from the JS classes.

Then there’s a bunch of improvements to the documentation.

As a heads-up/warning, AppLayout is going through a major iteration and will change quite significantly. It’s far from finished yet, though, so it’ll take some time for me to get this 0.4 ready.

**Comment by jouni** [comment]
Broke the build quite badly with the latest changes 😅 
Need to figure out how to handle dynamic imports with `polymer build`. Alternatively, change to unbundled build.

**Comment by lkraav** [comment]
Nice :+1: Much looking forward to the new app layout and drawer implementation!

**Comment by lkraav** [comment]
Are j-elements dead? :)

**Comment by jouni** [comment]
Hi @lkraav, long time since we last talked 😃 

Nice to hear you’re still interested in my little pet project. I would say it is still hibernating, sleeping over the ideas and solutions.

Is there something in particular that you’d be interested in seeing evolve, or are you asking just out of pure curiosity?

**Comment by lkraav** [comment]
> Hi @lkraav, long time since we last talked smiley
> 
> Nice to hear you’re still interested in my little pet project. I would say it is still hibernating, sleeping over the ideas and solutions.
> 
> Is there something in particular that you’d be interested in seeing evolve, or are you asking just out of pure curiosity?

I think it randomly displayed in some browser history search and reminded me that I should take a look at what's going on here, since you did have quite elegant solutions here at the time, for a couple of things we wanted (nav drawer was one).

For some reason in the morning https://jelements.netlify.app didn't seem to load, but now it does again, so I'll take a look around and refresh my memory.

Many new things have been implemented in vaadin/web-components by now, too.

**Comment by jouni** [comment]
> Many new things have been implemented in vaadin/web-components by now, too.

Yeah, and fortunately as better versions, that take for example a11y very seriously 😄 

I’m still holding out to a Tooltip component. And a better Field component eventually, which would make it easier to style all fields uniformly. And maybe we’ll eventually also solve web component styling in general 😆

**Pull request closed without merging**
